export const INPUT_FROM_NAME = 'INPUT_FROM_NAME';
export const INPUT_FROM_EMAIL = 'INPUT_FROM_EMAIL';
export const INPUT_TO_NAME = 'INPUT_TO_NAME';
export const INPUT_TO_EMAIL = 'INPUT_TO_EMAIL';
export const INPUT_THEME = 'INPUT_THEME';
export const INPUT_MSG = 'INPUT_MSG';
export const ATTACH_FILE = 'ATTACH_FILE';
export const DELETE_ATTACH_FILE = 'DELETE_ATTACH_FILE';

